version: "2.1"
services:
    app:
      build: ./app
      ports:
        - "8081:8080"
      links:
        - db
        - rserve
        - elasticsearch
      volumes:
        - app-data:/opt/molgenis
    db:
      build: ./db
      expose:
        - "5432"
      volumes:
        - db-data:/var/lib/postgresql/data
    rserve:
      build: ./rserve
      expose:
        - "6311"
      links:
        - app
    elasticsearch:
      image: elasticsearch:1.7.5
      expose:
        - "9200"
        - "9300"
      volumes:
        - elasticsearch-data:/usr/share/elasticsearch/data
volumes:
    db-data:
    app-data:
    elasticsearch-data:
